
services:
  app:
    build: .
    container_name: foodhub_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
      - API_SECURITY_TOKEN_SECRET=${API_SECURITY_TOKEN_SECRET}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: foodhub_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodhub
    ports:
      - "${POSTGRES_PORT}:5432"
    command: >
      postgres -c listen_addresses='*'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
